### ISSUE TITLE
VSD to SVG convert word wrap incorrect

### ISSUE THREAD

**Issue by liqiang** [LibreOffice/libvisio#2]
Hi,
   The word wrap seems always at the last characters not at words, so the converted SVG seems totally mess up when there are many word wrap text. And the LibreOffice export VSD to SVG works fine. 
   Is this a known issue or I am missing something ?

Thanks,
John

**Comment by xiangzhai** [comment]
More than that, the testcase https://github.com/LibreOffice/libvisio/tree/master/src/test/data of libvisio is too easy, if use Microsoft`s http://www.microsoft.com/zh-cn/download/details.aspx?id=24023 we have to fix conv tool`s issue!

Microsoft visio to png
![bldgplan](https://cloud.githubusercontent.com/assets/851100/8223510/25811812-15ab-11e5-82ba-ec8efd370839.png)

libvisio vsd2xhtml
![libvisio-snapshot2](https://cloud.githubusercontent.com/assets/851100/8223513/309d8eb0-15ab-11e5-9775-715d84cc5380.png)

**Comment by dtardon** [comment]
This is a read-only mirror. Nobody watches it. Bug reports should go to https://bugs.documentfoundation.org .
