### ISSUE TITLE
test (importtest.cpp) fails to compile on OS X w/ clang (call to function operator<<)

### ISSUE THREAD

**Issue by nieder** [LibreOffice/libvisio#3]
On OS X 10.9, with clang (Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)) and cppunit-1.12.1:

> clang++ -DHAVE_CONFIG_H -I. -I../..  -DTDOC=\"../../src/test/data\" -I/sw/opt/boost-1_58/include -I/sw/include -I../../inc -I/sw/include/librevenge-0.0  -I/sw/include/libxml2 -I/sw/include  -I/sw/include  --std=c++0x -I/sw/include/librevenge-0.0  -I/sw/include  -DNDEBUG -g -O2 -fvisibility=hidden -DLIBVISIO_VISIBILITY -Wall -Wextra -Wshadow -pedantic -MT test-importtest.o -MD -MP -MF .deps/test-importtest.Tpo -c -o test-importtest.o `test -f 'importtest.cpp' || echo './'`importtest.cpp
In file included from importtest.cpp:13:
In file included from /sw/include/cppunit/extensions/HelperMacros.h:9:
In file included from /sw/include/cppunit/TestCaller.h:5:
In file included from /sw/include/cppunit/TestCase.h:6:
/sw/include/cppunit/TestAssert.h:49:13: error: call to function 'operator<<' that is neither visible in the template definition nor found by
      argument-dependent lookup
        ost << x;
            ^
/sw/include/cppunit/TestAssert.h:101:50: note: in instantiation of member function 'CppUnit::assertion_traits<librevenge::RVNGString>::toString'
      requested here
    Asserter::failNotEqual( assertion_traits<T>::toString(expected),
                                                 ^
importtest.cpp:66:3: note: in instantiation of function template specialization 'CppUnit::assertEquals<librevenge::RVNGString>' requested here
  CPPUNIT_ASSERT_EQUAL_MESSAGE(message.cstr(), expectedValue, actualValue);
  ^
/sw/include/cppunit/TestAssert.h:214:17: note: expanded from macro 'CPPUNIT_ASSERT_EQUAL_MESSAGE'
  ( CPPUNIT_NS::assertEquals( (expected),              \
                ^
importtest.cpp:20:15: note: 'operator<<' should be declared prior to the call site or in namespace 'librevenge'
std::ostream &operator <<(std::ostream &s, const librevenge::RVNGString &string)
              ^
1 error generated.

**Comment by dtardon** [comment]
This is a read-only mirror. Nobody watches it. Bug reports should go to https://bugs.documentfoundation.org .
